In [ ]:
import pandas as pd

Read the csv file from this url:
'https://drive.google.com/file/d/1sXYEFFcJj0qlfqp08lPWaeuu_z35ICfp/view?usp=drive_link'

Name it `sets_df`

In [ ]:
# Your code here

> Make sure you save the changes by overwriting the original DataFrame:  
e.g. `df['name'] = df['name'].str.upper()`

#### Exercise 1
How long are the names? Does these value seem right?      
Look at a single name and see if you can figure out what is happening.

In [ ]:
# Your code here

#### Exercise 2
Remove the extra whiteshape from the `name` column.     
Check the length of the names again.

In [ ]:
# Your code here

#### Exercise 3
Change everything in the `name` column to lowercase.

In [ ]:
# Your code here

#### Exercise 4
How many names contain the string 'lego'?     
Select those sets.

In [ ]:
# Your code here

#### Exercise 5
What's the most words in one name? The least?

In [ ]:
# Your code here

#### Exercise 6
There are strange symbols around the set numbers. Remove them.

In [ ]:
# Your code here

#### Exercise 7
Set numbers are in two pieces, separated by '-'. Separate the two pieces from each other. Save the first part as a new column `set_num_prefix` and the second part as `set_num`.

In [ ]:
# Your code here

#### Exercise 8
Replace the word 'brick' in the column `name` with the word 'block'.     
Check after to make sure the word 'brick' is no longer in any name.

In [ ]:
# Your code here

#### Exercise 9
How many sets contain a number in the name?     
How many `set_num_prefix` contain **no** number?

In [ ]:
# Your code here